### ISSUE TITLE
Doesn't work with multiline history records

### ISSUE THREAD

**Issue by zdmytriv** [dvorka/hstr#329]
Doesn't work with multiline history records

```
echo """1
2
3
"""
```

after looking up in `hstr` it finds and inserts only `echo """1\` which only first line.

**Comment by dvorka** [comment]
I admit that this behavior is intentional as I didn't know how to fit multi-line history records in commands list nicely...

@zdmytriv @max-lobur would you have any suggestion/preference how can I improve HSTR? Like making multi-line command single line and indicating new lines using a character... any other idea?

**Comment by max-lobur** [comment]
@dvorka thanks for takin a look. "\n" will be totally ok, usually other lines are just args, I primarily search for a command name not args, so this will work. Kind of
```
command --arg 1 --arg 2 \n...
```

**Comment by dguendisch** [comment]
How about simply indenting the multilines by 1 or 2 whitespaces? As of now all history entries start on the very left, so indenting could be used to hint at a multiline entry.

**Comment by max-lobur** [comment]
You would lose to much useful space

**Comment by metaflow** [comment]
Am I also fine if it displays first line only as long as long as full version is used.

**Comment by ed-muthiah** [comment]
This would be super useful! Currently having a difficult time with ROS commands like:
```
rostopic pub -r 10 /husky_velocity_controller/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 
```
